[20기 문성호]마이페이지 구현
wecode-bootcamp-korea/20-1st-WESOP-backend pull request #14
Opened 2021-05-17 07:01 UTC by Room9

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- my page 구현 
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
-decorator를 통해 인가 받기
- 인가 후 스킨타입 / 주소 추가 및 삭제 가능

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-19 10:10 UTC, Kang-kyunghun commented on users/urls.py
> +            path('/userinfo', UserInformationView.as_view()),
```suggestion
            path('/information', UserInformationView.as_view()),
```
main url.py에 user가 이미 있기 때문에 다음과 같이 수정하면 좋을 것 같습니다.

2021-05-19 10:15 UTC, Kang-kyunghun requested changes

2021-05-19 10:15 UTC, Kang-kyunghun commented on users/views.py
> +        info = 'Nothing'
infor라는 변수 명은 명확하지 않습니다. 해당 변수가 무엇을 의미하는지 정확히 나타낼 수 있도록 바꿔 주시고 information을 infor처럼 줄이지 말아주세요.

2021-05-19 10:15 UTC, Kang-kyunghun commented on users/views.py
> +                skin_id           = skin.id if skin else ''
skin_id = '' 가 되었을 때  user.skin_type_id = skin_id 이부분에서 에러가 날 것 같은데 확인 바랍니다.

2021-05-19 10:15 UTC, Kang-kyunghun commented on users/utils.py
> +import  jwt
데코레이터 부분만 따로 브렌치 만들어서 머지 받으면 좋을 것 같아요

2021-05-19 10:58 UTC, Room9 commented on users/views.py
> +        info = 'Nothing'
넵 수정완료했습니다

2021-05-19 11:02 UTC, Room9 commented on users/views.py
> +                skin_id           = skin.id if skin else ''
skin_type = 'empty'로 요청했을 때, skin_id=''가 되는데 정상 구동 확인했습니다
![image](https://user-images.githubusercontent.com/79136484/118802507-28fec300-b8dd-11eb-9a28-f57b60270a68.png)

2021-05-19 11:03 UTC, Room9 commented on users/utils.py
> +import  jwt
따로 브랜치 만들어서 pr 올리겠습니다

2021-05-20 05:41 UTC, Kang-kyunghun requested changes

2021-05-20 05:41 UTC, Kang-kyunghun commented on .vscode/settings.json
> +}
성호님 계속 불피요한 파일들이 올라옵니다.

2021-05-20 05:41 UTC, Kang-kyunghun commented on users/views.py
> +from users.utils  import Authorization_decorator
import 라인에 맞춰주세요.

2021-05-20 05:50 UTC, Room9 commented on .vscode/settings.json
> +}
네넵 ignore 하겠습니다

2021-05-20 05:50 UTC, Room9 commented on users/views.py
> +from users.utils  import Authorization_decorator
넵 수정하겠습니다

2021-05-20 06:50 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-05-20 06:50 UTC, merged