[20기 양미화] 상품 정보 보내기 기능 - ProductListView
wecode-bootcamp-korea/20-1st-WESOP-backend pull request #19
Opened 2021-05-18 07:47 UTC by hwaya2828

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- merge된 main pull 받은 뒤 다시 branch 만들었습니다 😊
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

<img width="1440" alt="스크린샷 2021-05-18 오후 4 47 15" src="https://user-images.githubusercontent.com/75417394/118612450-bddbc080-b7f8-11eb-9f42-99a8a006035b.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-19 10:23 UTC, Kang-kyunghun requested changes

2021-05-19 10:23 UTC, Kang-kyunghun commented on products/views.py
> +        ingredient_ids     = request.GET.getlist('ingredient_id', None)
데이터 받는 부분은 위에서 다 하는 것이 더 가독성이 좋을 것 같아요

2021-05-19 10:23 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({'MESSAGE':'INVALID_PATH'}, status=404)
필터링 하려는 menu랑 category id 같은 경우는 해당 id가 없을 때는 어차피 빈 쿼리셋이 나오기 때문에 존재 여부를 판단하지 않아도 될 것 같습니다. product 기준으로 봤을 때 해당 매뉴나 카테고리에 속하지 않은 것으로 생각 되기 때문입니다.

2021-05-19 10:24 UTC, hwaya2828 commented on products/views.py
> +        ingredient_ids     = request.GET.getlist('ingredient_id', None)
넵 수정했습니다! 감사합니당!! 🥳

2021-05-19 10:26 UTC, hwaya2828 commented on products/views.py
> +            return JsonResponse({'MESSAGE':'INVALID_PATH'}, status=404)
아하! filter 되면서 자연스럽게 걸러지는 부분이었네요! 미처 생각하지 못했습니다!
수정했습니다 감사합니다 🥳

2021-05-19 10:41 UTC, Kang-kyunghun requested changes
다음 내용을 한 번 고민해 보고 수정해 보세여.
1. if가 중복적으로 계속 사용 되는 부분을 줄일 수 있는 방법
2. 저희가 계속 해결 못 하고 있는 같은 feature에 대한 filtering(2번을 후순위로)

2021-05-19 10:41 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({'MESSAGE':'INVALID_PATH'}, status=404)
존재 여부 판단을 안 하니까 이 부분은 이제 필요 없지 않을까요?

2021-05-19 10:59 UTC, hwaya2828 commented on products/views.py
> +            return JsonResponse({'MESSAGE':'INVALID_PATH'}, status=404)
앗 그러네요!!
if-elif 부분도 연결되야 할 이유 없어졌으니 각각 if문으로 수정했습니다 감사합니당 🥳

2021-05-20 02:34 UTC, hwaya2828 commented
q = Q()
        q.add(Q(category__menu_id=menu_id), q.OR)
        q.add(Q(category_id=category_id), q.OR)
        q.add(Q(name=search_name), q.OR)
        
검색 기능도 Q object 처리 하고 확인했습니다 :)

<img width="1440" alt="스크린샷 2021-05-20 오전 11 25 05" src="https://user-images.githubusercontent.com/75417394/118910372-4d02e880-b95f-11eb-86e0-dca6c6f07445.png">

2021-05-20 07:35 UTC, Kang-kyunghun commented
고생 많으셨습니다~!!

2021-05-20 07:35 UTC, merged

2021-05-20 07:37 UTC, hwaya2828 commented
경훈님 감사합니다!! 👍👍👍👍👍👍