[20기 문성호] 장바구니 구현
wecode-bootcamp-korea/20-1st-WESOP-backend pull request #20
Opened 2021-05-19 04:06 UTC by Room9

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 장바구니 추가 / 삭제 / 수정 / 조회 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- order_status 가 '주문 전'인 status를 가지는 order_id를 참조하도록 장바구니 구현
- 장바구니 추가 시, 이미 추가된 상품인 경우 상품의 갯수 +1 되도록 로직 구현
- 장바구니 내 특정 상품의 갯수 수정 로직 구현
- 장바구니 내 상품 삭제 / 조회 구현
- 하나의 class 내에서 method를 post/ patch / delete / get으로 구분하여 단일 endpoint에 묶이도록 했습니다

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 장바구니 추가 method 구현 시 update_or_create 활용하여 해당 상품이 장바구니에 이미 존재하는지 확인해보려했으나
수량을 +1 update 혹은 1로 create 하는 로직을 구분하지 못했는데 가능한지 궁금합니다

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-19 10:37 UTC, Kang-kyunghun requested changes

2021-05-19 10:37 UTC, Kang-kyunghun commented on CSV/category.csv
> +category,name,summary,thumbnail_url,description,content,content_image_url,count
csv 파일은 제거해 주세요.

2021-05-19 10:37 UTC, Kang-kyunghun commented on db_update.py
> +import os
updata 파일도 제거하고 gitignor에 추가해 주세요.

2021-05-19 10:37 UTC, Kang-kyunghun commented on orders/views.py
> +from users.utils     import Authorization_decorator
import 라인 맞춰주세요.

2021-05-19 10:37 UTC, Kang-kyunghun commented on orders/views.py
> +
주석은 제거해 주세요.

2021-05-19 10:37 UTC, Kang-kyunghun commented on orders/views.py
> +            cartlists   = OrderList.objects.all()
이렇게 되면 모든 orderlist가 다 담깁니다. 장바구니 목록을 보여주기 위한 view라고 하면 어떤 user의 것이고, 상태가 주문전인 orderlist을 가져와야 합니다.

2021-05-19 10:37 UTC, Kang-kyunghun commented on orders/views.py
> +                    'added_at':Order.objects.get(status_id=status_id).purchased_at
orderlist 데이터를 가져왔으면 그안에 product 정보들도 다 포함 되어 있을 것으로 예상됩니다. 가져온 orderlist로부터 데이터를 가져와 보세요.

2021-05-19 10:37 UTC, Kang-kyunghun commented on orders/views.py
> +    def post(self, request):
생선 부분은 구두로  이야기 하겠습니다.

2021-05-19 11:30 UTC, Room9 commented on CSV/category.csv
> +category,name,summary,thumbnail_url,description,content,content_image_url,count
네 알겠습니다!

2021-05-19 11:30 UTC, Room9 commented on db_update.py
> +import os
수정완료했습니다

2021-05-19 11:32 UTC, Room9 commented on orders/views.py
> +from users.utils     import Authorization_decorator
수정 완료했습니다

2021-05-19 11:33 UTC, Room9 commented on orders/views.py
> +
수정 완료했습니다

2021-05-19 12:14 UTC, Room9 commented on orders/views.py
> +            cartlists   = OrderList.objects.all()
user 구분 될 수 있도록 조건 추가했습니다

2021-05-19 12:15 UTC, Room9 commented on orders/views.py
> +                    'added_at':Order.objects.get(status_id=status_id).purchased_at
orderlist 테이블이 order와 productselection을 참조하기만하여, 정참조 이용하여 해당 data 가져왔습니다 수정 방안 내일 재문의 드리겠습니다

2021-05-19 12:16 UTC, Room9 commented on orders/views.py
> +    def post(self, request):
넵 우선 user_id 구분 추가했습니다 내일 재 문의 드리겠습니다.

2021-05-20 07:21 UTC, Kang-kyunghun requested changes

2021-05-20 07:21 UTC, Kang-kyunghun commented on orders/views.py
> +        )
```suggestion
            OrderList.objects.create(
            order_id = order.id,
            product_selection_id= selection.id,
            quantity = 1
        )        
```

2021-05-20 07:21 UTC, Kang-kyunghun commented on orders/views.py
> +        status_id = OrderStatus.objects.get(name='주문 전').id
```suggestion
        status = OrderStatus.objects.get(name='주문 전')
```

2021-05-20 07:21 UTC, Kang-kyunghun commented on orders/views.py
> +        order, created = Order.objects.get_or_create(status_id=status_id, user_id=user_id, defaults={
```suggestion
        order, created = Order.objects.get_or_create(status=status, user_id=user_id, defaults={
```

2021-05-20 11:45 UTC, Kang-kyunghun commented
LGTM

2021-05-20 11:46 UTC, merged