[20기 양미화] 상품 정보 보내기 기능 - PopularProductView
wecode-bootcamp-korea/20-1st-WESOP-backend pull request #21
Opened 2021-05-19 04:10 UTC by hwaya2828

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- TOP5 인기 상품 정보를 보내주는 기능
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

<img width="1440" alt="스크린샷 2021-05-19 오후 1 08 13" src="https://user-images.githubusercontent.com/75417394/118755300-93930d00-b8a3-11eb-90dd-df9e9fd6349f.png">

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-19 10:29 UTC, Kang-kyunghun requested changes

2021-05-19 10:29 UTC, Kang-kyunghun commented on products/views.py
> +        products = Product.objects.all().order_by('-count')[:5]
슬라이싱 한 5는 상수화 해주세요

2021-05-19 10:29 UTC, Kang-kyunghun commented on products/views.py
> +                    "product_ingredients"        : [ingredient.name for ingredient in ingredients],
```suggestion
                    "product_ingredients"        : [ingredient.name for ingredient in product.ingredient.all()],
```
계속 사용되는 변수가 아니므로 합치는 것이 어떨까 합니다.

2021-05-19 10:41 UTC, hwaya2828 commented on products/views.py
> +        products = Product.objects.all().order_by('-count')[:5]
넵 수정했습니다 감사합니당!!! 🥳

2021-05-19 10:42 UTC, hwaya2828 commented on products/views.py
> +                    "product_ingredients"        : [ingredient.name for ingredient in ingredients],
오 훨씬 보기 좋은것 같습니다!
product_selections 부분도 product.productselection_set.all()로 바꿔봤습니당 혹시 괜찮을까요?
수정했습니다 감사합니당!!! 🥳

2021-05-20 02:20 UTC, Kang-kyunghun commented
LGTM~~!!!

2021-05-20 02:20 UTC, merged