[20기 문성호]로그인 구현
wecode-bootcamp-korea/20-1st-WESOP-backend pull request #7
Opened 2021-05-14 06:55 UTC by Room9

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 로그인 시 jwt 리턴
![image](https://user-images.githubusercontent.com/79136484/118233311-b5b81400-b4cc-11eb-8520-eeaba2a13ccc.png)

		 
## 수정 사항들 자세한 내용
- 필수입력: email, password
- 로그인 완료 시, jwt return 설정(payload 내용: ID / token 만료기간)
- error 시, 상황에 맞는 messege 응답 
- decorator 구현 완료(request 내 token decode 정상 동작 확인)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-05-17 01:33 UTC, Kang-kyunghun requested changes

2021-05-17 01:33 UTC, Kang-kyunghun commented on users/utils.py
> +
불필요한 공백 제거해 주세요.

2021-05-17 01:33 UTC, Kang-kyunghun commented on users/utils.py
> +                request.user = user
들여쓰기 한 번 더 된 것 같아요

2021-05-17 06:33 UTC, Room9 commented on users/utils.py
> +
네 수정하겠습니다

2021-05-17 06:34 UTC, Room9 commented on users/utils.py
> +                request.user = user
네 수정하겠습니다

2021-05-18 02:41 UTC, jamessoun93 approved these changes
LGTM

2021-05-18 02:41 UTC, merged